### PR TITLE
[REFACTOR] Use WP-CLI via docker image rather than composer dep.

### PR DESCRIPTION
**Pull request by jenkoian**
Installing wp-cli via composer is fine, but it means we're at the mercy
of our other dependencies. i.e. we could hit a dependency version
conflict which could mean we couldn't install wp-cli or that other
library.

This uses the official docker image as part of our app image in much the
same way as we install composer itself.

Unfortunately (afaik) dependabot is unable to handle images within the
`COPY` command in docker, so we will need to keep the image up to date
ourselves.

Similarly, this commit also bumps the composer image we use to use the
latest version at time of writing (2.2.3).

### CODE REVIEW

**Review by jonny-bull — APPROVED** [review]

**Comment by andrewjt71** [comment]
Minor: typo in 2nd commit `The scaffold command is still required via compsoer`

**Comment by andrewjt71** [comment]
Question:

> Installing wp-cli via composer is fine, but it means we're at the mercy
of our other dependencies

I understand the reasoning behind this - in a nutshell, wp-cli is treated as an external lib which happens to be in php - it doesn't need to be compatible with our application code as it calls our application code externally like phpcs etc. So bringing it in via composer may raise conflicts which we don't care about.

However, seeing as we are now bringing `wp-cli` in via composer anyway (for the scaffolding command), doesn't this overhead still apply?

**Comment by jenkoian** [comment]
> However, seeing as we are now bringing wp-cli in via composer anyway (for the scaffolding command), doesn't this overhead still apply?

We are only bringing in the scaffold-command now as we extend it for our custom scaffolder. However, as this depends on `wp-cli/wp-cli` we bring that in also.

This is still a lower overhead to what was before which was bringing in `wp-cli/wp-cli-bundle` which I believe is what the docker image uses. We could also make the scaffold dep a suggestion if we wanted, further reducing the overhead. 

So I guess by decoupling wp-cli from our application we have more options (I'm struggling to quantify but it also just feels cleaner). 

Hope this helps clarify?

**Comment by andrewjt71** [comment]
> This is still a lower overhead to what was before which was bringing in wp-cli/wp-cli-bundle

Thanks @jenkoian, this is the piece of the puzzle I was missing

**Pull request merged**
