### PR TITLE
[DEPS] Updates Roots to use new full installation option

### PR DESCRIPTION
**Pull request by PeteWJ**
The Roots WordPress installation package has removed the default installation of themes, and therefore does not create the `wp-content` folder expected by the installer. This results in `wp core install` failing as it is unable to find expected folders.

The old approach - bundling the themes - is available as a separate package: `roots/wordpress-full`

This PR changes to that new package.

Details of the change in the package can be found here [https://roots.io/updates-to-roots-wordpress-composer-package/](https://roots.io/updates-to-roots-wordpress-composer-package/)

### CODE REVIEW

**Comment by anthonywnz** [comment]
It sounds like we can remove `roots/wordpress` then?

**Comment by PeteWJ** [comment]
@anthonywnz ... now that would make an awful lot of sense 🤦🏻

**Comment by anthonywnz** [comment]
Hmm... Maybe not... Or maybe we just need https://packagist.org/packages/roots/wordpress-core-installer too?

Let me know if you want me to pick this up :)

**Comment by PeteWJ** [comment]
@anthonywnz ... nice. I've just added that and built locally. Seems like the tests are happy too.
Are you able to pull a fresh copy down and check all is working for you?

**Pull request merged**
